version: '3.7'
services:
  api:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=psql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/potatoapi
      - SECRET_KEY
      - DEBUG
      - WAIT_HOSTS=db:5432
    env_file: .env
    networks:
      - potatoapi
    ports:
      - "8001:8080"
    volumes:
      - /home/potato/potatoapi/public:/app/public

  db:
    image: 'postgres:11-alpine'
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=potatoapi
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - potatoapi

  rsync:
    build: ./rsync
    restart: always
    depends_on:
      - api
    env_file: .env
    volumes:
      - /home/potato/potatoapi/public/ota:/public

volumes:
  db_data:
networks:
  potatoapi:
